name: woocom
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  flutter_localizations:
#    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  carousel_slider: ^4.2.1
  dotted_line: ^3.1.0
#  toast: ^0.3.0
  fluttertoast: ^8.1.2
  image_picker: ^0.8.6
  share_plus: ^6.3.0
  syncfusion_flutter_sliders: ^20.4.42
#  flutter_range_slider: ^1.5.0
  flutter_rating_bar: ^4.0.1
  flutter_facebook_auth: ^5.0.7
  intl: ^0.17.0
#  http: ^0.13.5
#  flutter_phoenix: ^1.1.0
#  google_sign_in: ^5.4.2
#  flutter_google_places:  ^0.3.0
  flutter_slidable: ^2.0.0
#  firebase_messaging: ^14.2.1
#  equatable: ^2.0.5
  shimmer_animation: ^2.1.0+1
  flutter_staggered_grid_view: ^0.6.2
#  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons c  lass.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/gadgets/apple/
    - assets/images/gadgets/asus/
    - assets/images/gadgets/buds/
    - assets/images/gadgets/camera/
    - assets/images/gadgets/Huawei/
    - assets/images/gadgets/laptop/
    - assets/images/gadgets/oneplus/
    - assets/images/gadgets/pixel/
    - assets/images/gadgets/samsung/
    - assets/images/gadgets/watch/
    - assets/images/gadgets/watch/apple/
    - assets/images/gadgets/watch/apple/AppleWatch5/
    - assets/images/gadgets/watch/apple/AppleWatch6/
    - assets/images/gadgets/watch/apple/AppleWatchNikeSE/
    - assets/images/gadgets/watch/apple/AppleWatchNikeSeries4/
    - assets/images/gadgets/watch/apple/AppleWatchNikeSeries5/
    - assets/images/gadgets/watch/apple/AppleWatchNikeSeries6/
    - assets/images/gadgets/watch/apple/AppleWatchNikeSeries7/
    - assets/images/gadgets/watch/apple/AppleWatchSE/
    - assets/images/gadgets/watch/apple/AppleWatchSeries3/
    - assets/images/gadgets/watch/apple/AppleWatchSeries4/
    - assets/images/gadgets/watch/apple/AppleWatchSeries5/
    - assets/images/gadgets/watch/apple/AppleWatchSeries6/
    - assets/images/gadgets/watch/apple/AppleWatchSeries7/
    - assets/images/gadgets/watch/samsung/
    - assets/images/gadgets/watch/samsung/SamsungGalaxyWatch/
    - assets/images/gadgets/watch/samsung/SamsungGalaxyWatch3/
    - assets/images/gadgets/watch/samsung/SamsungGalaxyWatch4/
    - assets/images/gadgets/watch/samsung/SamsungGalaxyWatch5/
    - assets/images/gadgets/watch/samsung/SamsungGalaxyWatchActive/
    - assets/images/gadgets/watch/samsung/SamsungGalaxyWatchClassic/
    - assets/images/gadgets/watch/samsung/SamsungGalaxyWatchFit/
    - assets/images/gadgets/watch/samsung/SamsungWatchGear/
    - assets/images/gadgets/watch/samsung/SamsungWatchGearFit/
    - assets/images/gadgets/watch/samsung/SamsungWatchGearS/
    - assets/images/gadgets/watch/samsung/SamsungWatchGearSport/
    - assets/images/gadgets/watch/samsung/SamsungWatchSmartCharm/
    - assets/images/product/
    - assets/images/brand/
    - assets/images/product/banner/
    - assets/images/gift/
    - assets/images/gift/bow/
    - assets/images/gift/multipleBag/
    - assets/images/gift/multipleBox/
    - assets/images/gift/ribbon/
    - assets/images/gift/singleBag/
    - assets/images/gift/singleGift/
    - assets/images/status/

    
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Futura
      fonts:
        - asset: fonts/Futura.ttf
    - family: Futura_Blk_BT
      fonts:
        - asset: fonts/Futura_Blk_BT.ttf
    - family: Futura_Bold
      fonts:
        - asset: fonts/Futura_Bold.ttf
    - family: Futura_Bold_font
      fonts:
        - asset: fonts/Futura_Bold_font.ttf
    - family: Futura_Bold_Italic_font
      fonts:
        - asset: fonts/Futura_Bold_Italic_font.ttf
    - family: Futura_Book_Font
      fonts:
        - asset: fonts/Futura_Book_Font.ttf
    - family: Futura_Book_Italic_couont
      fonts:
        - asset: fonts/Futura_Book_Italic_couont.ttf
    - family: Futura_CondensedLight
      fonts:
        - asset: fonts/Futura_CondensedLight.otf
    - family: Futura_Extra_Black_font
      fonts:
        - asset: fonts/Futura_Extra_Black_font.ttf
    - family: Futura_Heavy_font
      fonts:
        - asset: fonts/Futura_Heavy_font.ttf
    - family: Futura_Heavy_Italic_font
      fonts:
        - asset: fonts/Futura_Heavy_Italic_font.ttf
    - family: futura_light_bt
      fonts:
        - asset: fonts/futura_light_bt.ttf
    - family: Futura_Light_font
      fonts:
        - asset: fonts/Futura_Light_font.ttf
    - family: Futura_Light_Italic_font
      fonts:
        - asset: fonts/Futura_Light_Italic_font.ttf
    - family: futura_medium_bt
      fonts:
        - asset: fonts/futura_medium_bt.ttf
    - family: futura_medium_condensed_bt
      fonts:
        - asset: fonts/futura_medium_condensed_bt.ttf
    - family: Futura_Medium_Italic_font
      fonts:
        - asset: fonts/Futura_Medium_Italic_font.ttf
    - family: Unicode_Futurab
      fonts:
        - asset: fonts/Unicode_Futurab.ttf
    - family: Unicode_futurab_Bold
      fonts:
        - asset: fonts/Unicode_futurab_Bold.ttf






  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
